version: "3.8"

name: h24s_24
services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=app #TODO: アプリ名に変える

  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app #TODO: アプリ名に変える
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    expose:
      - 3306
    ports:
      - 3306:3306

  adminer:
    image: adminer:latest
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  mysql:
